apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: express
  name: express
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: express
    spec:
      containers:
      - env:
        - name: WAIT_HOSTS
          value: mongo:27017
        image: raj72616a/expense-book-web:latest
        name: express
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
